from app.generators.base import InfrastructureGenerator
from app.models.infrastructure import InfrastructureSpec


class BasicTerraformGenerator(InfrastructureGenerator):
    def generate(self, spec: InfrastructureSpec) -> str:
        return (
            "# Generated by Infra Morph Lite\n"
            f"# Project: {spec.name}\n"
        )