from pathlib import Path

from app.services.generation import InfrastructureGenerationService


def test_generation_service_writes_output(tmp_path: Path):
    output_path = tmp_path / "main.tf"

    result = InfrastructureGenerationService().generate(
        "demo",
        output_path=output_path,
    )

    assert result == (
        "# Generated by Infra Morph Lite\n"
        "# Project: demo\n"
    )

    assert output_path.exists()
    assert output_path.read_text(encoding="utf-8") == result