from pathlib import Path

from app.services.output import TerraformOutputService


def test_output_service_writes_file(tmp_path: Path):
    output_path = tmp_path / "main.tf"

    TerraformOutputService().write(
        "# Generated by Infra Morph Lite\n",
        output_path,
    )

    assert output_path.exists()
    assert output_path.read_text(encoding="utf-8") == (
        "# Generated by Infra Morph Lite\n"
    )