from app.services.generation import InfrastructureGenerationService


def test_generation_service():
    service = InfrastructureGenerationService()

    result = service.generate("demo")

    assert result == (
        "# Generated by Infra Morph Lite\n"
        "# Project: demo\n"
    )