from pathlib import Path

from app.cli.main import main


def test_generate_command_writes_output(tmp_path: Path, monkeypatch):
    output_path = tmp_path / "main.tf"

    monkeypatch.setattr(
        "sys.argv",
        [
            "infra-morph",
            "generate",
            "demo",
            "--output",
            str(output_path),
        ],
    )

    main()

    assert output_path.exists()
    assert output_path.read_text(encoding="utf-8") == (
        "# Generated by Infra Morph Lite\n"
        "# Project: demo\n"
    )