import pytest
from app.cli.main import main

def test_generate_command(capsys, monkeypatch):
    monkeypatch.setattr(
        "sys.argv",
        ["infra-morph", "generate", "demo"],
    )

    main()

    captured = capsys.readouterr()

    assert captured.out == (
        "# Generated by Infra Morph Lite\n"
        "# Project: demo\n"
    )

def test_generate_command_requires_name(monkeypatch):
    monkeypatch.setattr(
        "sys.argv",
        ["infra-morph", "generate"],
    )

    with pytest.raises(SystemExit) as exc_info:
        main()

    assert exc_info.value.code == 2