from app.generators.terraform.basic import BasicTerraformGenerator
from app.models.infrastructure import InfrastructureSpec


def test_basic_terraform_generator():
    spec = InfrastructureSpec(name="demo")

    result = BasicTerraformGenerator().generate(spec)

    assert result == (
        "# Generated by Infra Morph Lite\n"
        "# Project: demo\n"
    )